apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
    group: go-samples
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: echo-server
      group: go-samples
  template:
    metadata:
      labels:
        app: echo-server
        group: go-samples
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      containers:
        - name: echo-server
          image: go-samples/echo-server:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: echo-server
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
            - name: probes
              containerPort: 9091
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /live
              port: 9091
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
