apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo-server
    group: go-samples
spec:
  selector:
    app: echo-server
    group: go-samples
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
    - name: probes
      port: 9091
      targetPort: probes
