apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo-server
    group: sample
spec:
  type: NodePort
  selector:
    app: echo-server
    group: sample
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: http-probes
      port: 9091
      targetPort: 9091
      protocol: TCP
