apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: echo-server
  labels:
    app: echo-server
    group: go-samples
spec:
  selector:
    matchLabels:
      app: echo-server
      group: go-samples
  # namespaceSelector:
  #   matchNames:
  #     - default
  endpoints:
    - port: metrics
      # path: /metrics
      interval: 15s
      scrapeTimeout: 14s
